### ISSUE TITLE
Asset Pipeline Help

### ISSUE THREAD

**Issue by searchforac** [WDI-Persephone-Project-3/Quiz-App#39]
Having problems with asset pipeline and integrating it with the public folder.  I have css and js in both right now and when i tried moving everything into the asset pipeline folders the css was not right.

**Comment by annarankin** [comment]
Hey Suhyun! What seems to be the problem?

**Comment by searchforac** [comment]
not able to get the heroku working.  fine on our local server but not working on heroku. i tried putting all the css and javasript in the asset pipeline but it did not work.
